# Puerto del gateway (unico punto de entrada para el cliente)
quarkus.http.port=8080

# URLs internas de cada microservicio
quarkus.rest-client.productos-api.url=http://localhost:8081
quarkus.rest-client.tiendas-api.url=http://localhost:8082
quarkus.rest-client.usuarios-api.url=http://localhost:8083
quarkus.rest-client.reportes-api.url=http://localhost:8084

# CORS: permite peticiones desde el browser y desde cliente-prueba.html
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Fixes NetBeans/Windows
quarkus.test.continuous-testing=disabled
quarkus.debug.suspend=false
quarkus.log.category."org.aesh".level=OFF
quarkus.log.category."io.quarkus.dev".level=WARN

quarkus.application.name=api-gateway
