# Puerto del gateway (unico punto de entrada para el cliente)
quarkus.http.port=8080

# URLs internas de cada microservicio
quarkus.rest-client.productos-api.url=http://localhost:8081
quarkus.rest-client.tiendas-api.url=http://localhost:8082
quarkus.rest-client.usuarios-api.url=http://localhost:8083
quarkus.rest-client.reportes-api.url=http://localhost:8084
quarkus.rest-client.busqueda-api.url=http://localhost:8086

# CORS: permite peticiones desde el browser y desde cliente-prueba.html
quarkus.http.cors=true
quarkus.http.cors.origins=*

# JWT: misma clave publica que usa ms-usuarios para firmar
# El gateway verifica el token y aplica @RolesAllowed en cada endpoint
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvVqih+l6/zFpV7Qv/8GWuct+LiXOkutK2nN1Df97B+yuOYkRd0xXAlzzlxuB6Lbi9nx3890xcAlcsKlG+L28i/MFt76QGs2X1iR2C9QRaaWVFKvNqquAkGsy7FYIzYKbLGViPDo1L6/euGXQRus1Y+n/6RHPaWSaNkIDGZHnpTaEdLOkDtVAqrXjSLtb3GD7N+L2JuOViz+lkPREHFP5CoF5+Z14xQ6BTs7SHmtpUIfU7MwVOAgDNIc0+qBQox+AISKjaJDilAiKuVq7IBFj0Rl20ZBnV2hhvGlt4qejvhkxtonSQ87+L3KFQ31m+2s/nK1uRSc7fcCm6i5QhrfTmwIDAQAB
mp.jwt.verify.issuer=profeco-app

# Fixes NetBeans/Windows
quarkus.test.continuous-testing=disabled
quarkus.debug.suspend=false
quarkus.log.category."org.aesh".level=OFF
quarkus.log.category."io.quarkus.dev".level=WARN

quarkus.application.name=api-gateway
