quarkus.http.port=8083

# Base de datos H2 en memoria
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/usuariosdb;AUTO_SERVER=TRUE
quarkus.datasource.username=sa
quarkus.datasource.password=

quarkus.hibernate-orm.database.generation=drop-and-create

# JWT \u00e2\u0080\u0094 claves RSA incrustadas directamente (no requiere archivos PEM ni openssl)
# Clave publica para VERIFICAR tokens entrantes
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvVqih+l6/zFpV7Qv/8GWuct+LiXOkutK2nN1Df97B+yuOYkRd0xXAlzzlxuB6Lbi9nx3890xcAlcsKlG+L28i/MFt76QGs2X1iR2C9QRaaWVFKvNqquAkGsy7FYIzYKbLGViPDo1L6/euGXQRus1Y+n/6RHPaWSaNkIDGZHnpTaEdLOkDtVAqrXjSLtb3GD7N+L2JuOViz+lkPREHFP5CoF5+Z14xQ6BTs7SHmtpUIfU7MwVOAgDNIc0+qBQox+AISKjaJDilAiKuVq7IBFj0Rl20ZBnV2hhvGlt4qejvhkxtonSQ87+L3KFQ31m+2s/nK1uRSc7fcCm6i5QhrfTmwIDAQAB
mp.jwt.verify.issuer=profeco-app

# Clave privada para FIRMAR tokens generados en el login
smallrye.jwt.sign.key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9WqKH6Xr/MWlXtC//wZa5y34uJc6S60rac3UN/3sH7K45iRF3TFcCXPOXG4HotuL2fHfz3TFwCVywqUb4vbyL8wW3vpAazZfWJHYL1BFppZUUq82qq4CQazLsVgjNgpssZWI8OjUvr964ZdBG6zVj6f/pEc9pZJo2QgMZkeelNoR0s6QO1UCqteNIu1vcYPs34vYm45WLP6WQ9EQcU/kKgXn5nXjFDoFOztIea2lQh9TszBU4CAM0hzT6oFCjH4AhIqNokOKUCIq5WrsgEWPRGXbRkGdXaGG8aW3ip6O+GTG2idJDzv4vcoVDfWb7az+crW5FJzt9wKbqLlCGt9ObAgMBAAECggEAVxb9IxK1YfMZdt+mpfSlfO3Fqrbz1GoI4wFwaJBFR2dJ2Kec02hWqn0TAkCCFwUqzWCBETX+e3+q1Iv+2v/1XM7ZJeItSE6gE7twWc9fdN5V+4xrSyCXQJU1djK52L/F2/0DWh0Rgk3a26fkTAH5a+tfqxRod5pwPR1ObK/JQZhN3rs09tt9jQndXqQuj/Fvohp0gbsusqwCUzgaeTQk9sfDM6DRvSH1hc/tocmsMqAurMGOuiuZB1a4r0E81+7A9ORfDqRpcb1oMeMiQSkFgnJGTKNU40MjsVUyvyw868RCABpC046XVTBQ7OHo+TuAkMo/idmGnegdlgPRM5uobQKBgQD5v/luLXliHQ0Lx627uywPMdK3lC4frb+ZtQpBbVa4gRV9EcqIow2iydMbBTaKxBfjZkgii+1fJ058fHUmtmE2+X/p8bzLdDjJ4V25wf+PhJ+/WeGxkVsuWc5VUB0eaqpVUPza/Agq0xwqda0SVdJX5R2cKg9ZeRD2S3oflSz8pQKBgQDCF7vZE6v2mdxFm3Hbqh42CAHyDuIc6BkBUCQsUEdW22YEel26NPzgThBR19rHsQApD8gLfbmu4o8kEuLDsXUHyHTGCJ+pkDndg3euYC2E7YEhA9DSaltUALQs1E1uDy+kHWRYNUvu13V+SCCDoysii6Z+hW75fCnpod00zMtbPwKBgDxspfxyJBwIy08+UFpLPq2ucDzaLQ6dCu41TvXlbkXVdU19MHM+f94S1nCDIl8QcnciF/HDyPpsmCCmO/HRzlNuqfP/+J2A0PyG+hYnSZ1/iObS6Df94wGj2LfrWiAxzmQ14/dXYuJ5kSb0sZruCKYbWL6frncHQ4NTX4iknu3BAoGAbEi3eYVbFCqE1KTDoezIDBbtlvEsvznR8YSXmc1z74ZZ5TeroN49Epsayb5mhbA/SalPTvHmrSYi+9o5fzo684uncnCPOxeG4QmetL9dxeKHfzbUwv+pUjVOUBBl3nhEeQgY2olpgqfcGgb9dNOMlipZSg8BedkGvRycAAAdmBsCgYEA2PRe2WzosxzxGtgFJkUSemYNFv1/SH3851wjfztcUxJNQo/Se+l3wBmqxGdk1gTwPyV3g0N+VnCkm5zmsT/4k74S93J/6mqznakx1m5DnDYEL27n6+ROgFt5AHLS+/H6+ZZnUWNMX52J5MRlGfqeQgcNECcYlSfD4SOWky5q9N8=
smallrye.jwt.new-token.lifespan=3600

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Fixes NetBeans/Windows
quarkus.test.continuous-testing=disabled
quarkus.debug.suspend=false
quarkus.log.category."org.aesh".level=OFF
quarkus.log.category."io.quarkus.dev".level=WARN

quarkus.application.name=ms-usuarios
