apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\PC\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f C:/Users/PC/Documents/NetBeansProjects/profeco/docker-compose.yml -o C:/Users/PC/Documents/NetBeansProjects/profeco/k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: ms-productos
  name: ms-productos
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: ms-productos
