apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-reportes
  labels:
    io.kompose.service: ms-reportes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms-reportes
  template:
    metadata:
      labels:
        io.kompose.service: ms-reportes
    spec:
      containers:
        - name: ms-reportes
          image: ms-reportes
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: QUARKUS_HTTP_PORT
              value: "8084"
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: postgresql
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/reportesdb
            - name: QUARKUS_DATASOURCE_USERNAME
              value: postgres
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profeco-db
                  key: password
            - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
              value: update
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
