apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\PC\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f C:/Users/PC/Documents/NetBeansProjects/profeco/docker-compose.yml -o C:/Users/PC/Documents/NetBeansProjects/profeco/k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\PC\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f C:/Users/PC/Documents/NetBeansProjects/profeco/docker-compose.yml -o C:/Users/PC/Documents/NetBeansProjects/profeco/k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3-management-alpine
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 5
          name: profeco-rabbitmq
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
      restartPolicy: Always
