quarkus.http.port=8081

# Base de datos PostgreSQL
# Las env vars QUARKUS_DATASOURCE_* sobreescriben estos valores en Docker.
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/productosdb
quarkus.datasource.username=postgres
quarkus.datasource.password=${DB_PASSWORD}

quarkus.hibernate-orm.database.generation=update

rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

mp.messaging.outgoing.ofertas-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ofertas-out.exchange.name=ofertas
mp.messaging.outgoing.ofertas-out.exchange.type=fanout
mp.messaging.outgoing.ofertas-out.routing-key=

quarkus.http.cors=true
quarkus.http.cors.origins=*

quarkus.test.continuous-testing=disabled
quarkus.debug.suspend=false
quarkus.log.category."org.aesh".level=OFF
quarkus.log.category."io.quarkus.dev".level=WARN

quarkus.application.name=ms-productos