# Puerto HTTP (para el endpoint REST que usa el gateway)
quarkus.http.port=8086

# Puerto gRPC (para comunicacion interna entre microservicios)
quarkus.grpc.server.port=9000

# URLs de los microservicios internos que consulta este servicio
quarkus.rest-client.productos-interno.url=http://localhost:8081
quarkus.rest-client.tiendas-interno.url=http://localhost:8082

# CORS para el cliente HTML
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Fixes NetBeans/Windows

quarkus.debug.suspend=false



quarkus.application.name=ms-busqueda

# Desactiva completamente los tests continuos y la consola interactiva
quarkus.test.continuous-testing=disabled
quarkus.dev-mode.instrumentation.enabled=false
quarkus.live-reload.instrumentation=false

# Silencia el error de terminal de Windows
quarkus.log.category."org.aesh".level=OFF
quarkus.log.category."io.quarkus.dev".level=OFF
quarkus.log.category."org.aesh.readline".level=OFF