quarkus.http.port=8085

# RabbitMQ
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# Canal de entrada \u2014 escucha ofertas publicadas por ms-productos
mp.messaging.incoming.ofertas-in.connector=smallrye-rabbitmq
mp.messaging.incoming.ofertas-in.exchange.name=ofertas
mp.messaging.incoming.ofertas-in.exchange.type=fanout
mp.messaging.incoming.ofertas-in.queue.name=cola-notificaciones-ofertas
mp.messaging.incoming.ofertas-in.queue.durable=true

# Canal de entrada \u2014 escucha alertas publicadas por ms-reportes
mp.messaging.incoming.inconsistencias-in.connector=smallrye-rabbitmq
mp.messaging.incoming.inconsistencias-in.exchange.name=inconsistencias
mp.messaging.incoming.inconsistencias-in.exchange.type=fanout
mp.messaging.incoming.inconsistencias-in.queue.name=cola-notificaciones-inconsistencias
mp.messaging.incoming.inconsistencias-in.queue.durable=true

# Fixes NetBeans/Windows
quarkus.test.continuous-testing=disabled
quarkus.debug.suspend=false
quarkus.log.category."org.aesh".level=OFF
quarkus.log.category."io.quarkus.dev".level=WARN

quarkus.application.name=ms-notificaciones

quarkus.http.cors=true
quarkus.http.cors.origins=*